DROP SEQUENCE IF EXISTS PUBLIC.HIBERNATE_SEQUENCE;
DROP SEQUENCE IF EXISTS PUBLIC.SEQ_TREATMENT;
DROP SEQUENCE IF EXISTS PUBLIC.SEQ_EMPLOYEE;
DROP SEQUENCE IF EXISTS PUBLIC.SEQ_APPOINTMENT;
DROP SEQUENCE IF EXISTS PUBLIC.SEQ_CLIENT;
DROP TABLE IF EXISTS PUBLIC.ADMIN;
DROP TABLE IF EXISTS PUBLIC.APPOINTMENT;
DROP TABLE IF EXISTS PUBLIC.CLIENT;
DROP TABLE IF EXISTS PUBLIC.COMPANY;
DROP TABLE IF EXISTS PUBLIC.EMPLOYEE;
DROP TABLE IF EXISTS PUBLIC.TREATMENT;
CREATE USER IF NOT EXISTS SA SALT '937e86497e02619c' HASH '46ad8998fc224839c6f085a61dc57b79305dec3d0ae9196f211e06f71f8b0340' ADMIN;           
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;       
CREATE SEQUENCE PUBLIC.SEQ_TREATMENT START WITH 1 INCREMENT BY 1;           
CREATE SEQUENCE PUBLIC.SEQ_EMPLOYEE START WITH 1 INCREMENT BY 1;             
CREATE SEQUENCE PUBLIC.SEQ_APPOINTMENT START WITH 1 INCREMENT BY 1;          
CREATE SEQUENCE PUBLIC.SEQ_CLIENT START WITH 1 INCREMENT BY 1; 
CREATE CACHED TABLE PUBLIC.ADMIN(
    ID BIGINT NOT NULL,
    EMAIL VARCHAR(255),
    NAME VARCHAR(255),
    NIF VARCHAR(255),
    PASSWORD VARCHAR(255),
    PHONE VARCHAR(255),
    PROFILEPIC VARCHAR(255)
);         
          
CREATE CACHED TABLE PUBLIC.APPOINTMENT(
    ID BIGINT NOT NULL,
    ENDTIME TIMESTAMP,
    ORDERDATE TIMESTAMP,
    PAID BOOLEAN NOT NULL,
    STARTTIME TIMESTAMP,
    CLIENT_ID BIGINT,
    EMPLOYEE_ID BIGINT,
    TREATMENT_ID BIGINT
);                       
 
CREATE CACHED TABLE PUBLIC.CLIENT(
    ID BIGINT NOT NULL,
    DNI VARCHAR(255),
    DUEPAYMENT BOOLEAN NOT NULL,
    EMAIL VARCHAR(255),
    HISTORICAL BOOLEAN NOT NULL,
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    PHONE VARCHAR(255),
    PROFILEPIC VARCHAR(255),
    REGISTERDATE TIMESTAMP,
    COMPANY_ID BIGINT
);                
          
CREATE CACHED TABLE PUBLIC.COMPANY(
    ID BIGINT NOT NULL,
    ADDRESS VARCHAR(255),
    CLOSETIME TIME,
    EMAIL VARCHAR(255),
    NAME VARCHAR(255),
    NIF VARCHAR(255),
    OPENTIME TIME,
    PHONE VARCHAR(255)
);        
     
CREATE CACHED TABLE PUBLIC.EMPLOYEE(
    ID BIGINT NOT NULL,
    DNI VARCHAR(255),
    EMAIL VARCHAR(255),
    GROSSANUALSALARY DOUBLE NOT NULL,
    HIREDATE TIMESTAMP,
    HISTORICAL BOOLEAN NOT NULL,
    HISTORICALDATE TIMESTAMP,
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    PHONE VARCHAR(255),
    POSITION VARCHAR(255),
    PROFILEPIC VARCHAR(255),
    COMPANY_ID BIGINT
);                              

CREATE CACHED TABLE PUBLIC.TREATMENT(
    ID BIGINT NOT NULL,
    DESCRIPTION VARCHAR(255),
    DISCOUNT INTEGER NOT NULL,
    HISTORICAL BOOLEAN NOT NULL,
    NAME VARCHAR(255),
    NUMSESSIONS INTEGER NOT NULL,
    PAIDININSTALLMENTS BOOLEAN NOT NULL,
    PICTURE VARCHAR(255),
    TOTALPRICE DOUBLE NOT NULL,
    COMPANY_ID BIGINT
);   
ALTER TABLE PUBLIC.CLIENT ADD CONSTRAINT PUBLIC.UK_F07YMTQAIF0TBCAWYB71L3ONE UNIQUE(EMAIL);   
ALTER TABLE PUBLIC.TREATMENT ADD CONSTRAINT PUBLIC.UK_SGA29CWGQ9CKCFS991CXD52VN UNIQUE(NAME); 
ALTER TABLE PUBLIC.EMPLOYEE ADD CONSTRAINT PUBLIC.UK_2Y5G3IJ0KGTVRLP3RTMJLABJ4 UNIQUE(EMAIL); 
ALTER TABLE PUBLIC.CLIENT ADD CONSTRAINT PUBLIC.UK_JJFVTU1OMVYVB8CWSDFFDO3K7 UNIQUE(DNI);     
ALTER TABLE PUBLIC.EMPLOYEE ADD CONSTRAINT PUBLIC.UK_RBEJ3POIHVY9B078TAISP2UPR UNIQUE(DNI);   